; File initially autogenerated by ./scripts/dump_tilesets.py

SECTION "Tileset TextAdditional", ROMX[$4AD1], BANK[$01]
TilesetTextAdditional::
  INCBIN "./build/gfx/tilesets/TextAdditional.compressed"

SECTION "Tileset NormalCharacters", ROMX[$5000], BANK[$01]
TilesetNormalCharacters::
  INCBIN "./build/gfx/tilesets/NormalCharacters.2bpp"

SECTION "Tileset DoubleHeightCharacters", ROMX[$6000], BANK[$01]
TilesetDoubleHeightCharacters::
  INCBIN "./build/gfx/tilesets/DoubleHeightCharacters.2bpp"

