; File initially autogenerated by ./scripts/dump_tilesets.py

SECTION "Tileset TextAdditional1", ROMX[$4A2F], BANK[$01]
TilesetTextAdditional1::
  INCBIN "./build/gfx/tilesets/TextAdditional1.compressed"
SECTION "Tileset TextAdditional1 End", ROMX[$4AD0], BANK[$01]

SECTION "Tileset TextAdditional2", ROMX[$4AD1], BANK[$01]
TilesetTextAdditional2::
  INCBIN "./build/gfx/tilesets/TextAdditional2.compressed"
SECTION "Tileset TextAdditional2 End", ROMX[$4BDA], BANK[$01]

SECTION "Tileset NormalCharacters", ROMX[$5000], BANK[$01]
TilesetNormalCharacters::
  INCBIN "./build/gfx/tilesets/NormalCharacters.2bpp"
SECTION "Tileset NormalCharacters End", ROMX[$5AFF], BANK[$01]

SECTION "Tileset DoubleHeightCharacters", ROMX[$6000], BANK[$01]
TilesetDoubleHeightCharacters::
  INCBIN "./build/gfx/tilesets/DoubleHeightCharacters.2bpp"
SECTION "Tileset DoubleHeightCharacters End", ROMX[$75FF], BANK[$01]

