; File initially autogenerated by ./scripts/dump_text.py
INCLUDE "./build/dialog/text_constants.asm"

SECTION "Text banks", ROMX[$4083], BANK[$02]
TextBanks::
  db BANK(TextBank00)
  db BANK(TextBank01)
  db BANK(TextBank02)
  db BANK(TextBank03)
  db BANK(TextBank04)
  db BANK(TextBank05)
  db BANK(TextBank06)
  db BANK(TextBank07)
  db BANK(TextBank08)
  db BANK(TextBank09)
  db BANK(TextBank0A)
  db BANK(TextBank0B)
  db BANK(TextBank0C)
  db BANK(TextBank0D)
  db BANK(TextBank0E)
  db BANK(TextBank0F)
  db BANK(TextBank10)
  db BANK(TextBank11)

SECTION "Text Bank 00", ROMX[$4F0D], BANK[$60]
TextBank00::
  dw cTextGroup00_00
  dw cTextGroup00_01
  dw cTextGroup00_02
  dw cTextGroup00_03
  dw cTextGroup00_04
  dw cTextGroup00_05
  dw cTextGroup00_06
  dw cTextGroup00_07
  dw cTextGroup00_08
  dw cTextGroup00_09
  dw cTextGroup00_0A
  dw cTextGroup00_0B
  dw cTextGroup00_0C
  dw cTextGroup00_0D
  dw cTextGroup00_0E

SECTION "Text_00", ROMX[$4F2B], BANK[$60]
  INCBIN cText_00

SECTION "Text Bank 01", ROMX[$4039], BANK[$61]
TextBank01::
  dw cTextGroup01_00
  dw cTextGroup01_01
  dw cTextGroup01_02
  dw cTextGroup01_03
  dw cTextGroup01_04
  dw cTextGroup01_05
  dw cTextGroup01_06
  dw cTextGroup01_07
  dw cTextGroup01_08

SECTION "Text_01", ROMX[$404B], BANK[$61]
  INCBIN cText_01

SECTION "Text Bank 02", ROMX[$4039], BANK[$62]
TextBank02::
  dw cTextGroup02_00
  dw cTextGroup02_01
  dw cTextGroup02_02
  dw cTextGroup02_03
  dw cTextGroup02_04
  dw cTextGroup02_05
  dw cTextGroup02_06
  dw cTextGroup02_07
  dw cTextGroup02_08
  dw cTextGroup02_09
  dw cTextGroup02_0A
  dw cTextGroup02_0B
  dw cTextGroup02_0C
  dw cTextGroup02_0D
  dw cTextGroup02_0E
  dw cTextGroup02_0F
  dw cTextGroup02_10
  dw cTextGroup02_11
  dw cTextGroup02_12
  dw cTextGroup02_13

SECTION "Text_02", ROMX[$4061], BANK[$62]
  INCBIN cText_02

SECTION "Text Bank 03", ROMX[$4039], BANK[$63]
TextBank03::
  dw cTextGroup03_00
  dw cTextGroup03_01
  dw cTextGroup03_02
  dw cTextGroup03_03
  dw cTextGroup03_04
  dw cTextGroup03_05
  dw cTextGroup03_06
  dw cTextGroup03_07
  dw cTextGroup03_08
  dw cTextGroup03_09
  dw cTextGroup03_0A
  dw cTextGroup03_0B
  dw cTextGroup03_0C
  dw cTextGroup03_0D
  dw cTextGroup03_0E
  dw cTextGroup03_0F
  dw cTextGroup03_10
  dw cTextGroup03_11
  dw cTextGroup03_12
  dw cTextGroup03_13
  dw cTextGroup03_14
  dw cTextGroup03_15
  dw cTextGroup03_16

SECTION "Text_03", ROMX[$4067], BANK[$63]
  INCBIN cText_03

SECTION "Text Bank 04", ROMX[$4039], BANK[$64]
TextBank04::
  dw cTextGroup04_00
  dw cTextGroup04_01
  dw cTextGroup04_02
  dw cTextGroup04_03
  dw cTextGroup04_04

SECTION "Text_04", ROMX[$4043], BANK[$64]
  INCBIN cText_04

SECTION "Text Bank 05", ROMX[$4039], BANK[$65]
TextBank05::
  dw cTextGroup05_00
  dw cTextGroup05_01
  dw cTextGroup05_02
  dw cTextGroup05_03
  dw cTextGroup05_04
  dw cTextGroup05_05
  dw cTextGroup05_06
  dw cTextGroup05_07

SECTION "Text_05", ROMX[$4049], BANK[$65]
  INCBIN cText_05

SECTION "Text Bank 06", ROMX[$4039], BANK[$66]
TextBank06::
  dw cTextGroup06_00
  dw cTextGroup06_01
  dw cTextGroup06_02
  dw cTextGroup06_03
  dw cTextGroup06_04
  dw cTextGroup06_05

SECTION "Text_06", ROMX[$4045], BANK[$66]
  INCBIN cText_06

SECTION "Text Bank 07", ROMX[$4039], BANK[$67]
TextBank07::
  dw cTextGroup07_00
  dw cTextGroup07_01
  dw cTextGroup07_02
  dw cTextGroup07_03
  dw cTextGroup07_04
  dw cTextGroup07_05
  dw cTextGroup07_06
  dw cTextGroup07_07
  dw cTextGroup07_08
  dw cTextGroup07_09
  dw cTextGroup07_0A
  dw cTextGroup07_0B

SECTION "Text_07", ROMX[$4051], BANK[$67]
  INCBIN cText_07

SECTION "Text Bank 08", ROMX[$4039], BANK[$68]
TextBank08::
  dw cTextGroup08_00
  dw cTextGroup08_01
  dw cTextGroup08_02
  dw cTextGroup08_03
  dw cTextGroup08_04
  dw cTextGroup08_05
  dw cTextGroup08_06

SECTION "Text_08", ROMX[$4047], BANK[$68]
  INCBIN cText_08

SECTION "Text Bank 09", ROMX[$4039], BANK[$69]
TextBank09::
  dw cTextGroup09_00
  dw cTextGroup09_01
  dw cTextGroup09_02
  dw cTextGroup09_03
  dw cTextGroup09_04
  dw cTextGroup09_05
  dw cTextGroup09_06
  dw cTextGroup09_07
  dw cTextGroup09_08
  dw cTextGroup09_09
  dw cTextGroup09_0A
  dw cTextGroup09_0B
  dw cTextGroup09_0C
  dw cTextGroup09_0D
  dw cTextGroup09_0E
  dw cTextGroup09_0F
  dw cTextGroup09_10
  dw cTextGroup09_11
  dw cTextGroup09_12

SECTION "Text_09", ROMX[$405F], BANK[$69]
  INCBIN cText_09

SECTION "Text Bank 0A", ROMX[$4039], BANK[$6A]
TextBank0A::
  dw cTextGroup0A_00
  dw cTextGroup0A_01
  dw cTextGroup0A_02
  dw cTextGroup0A_03
  dw cTextGroup0A_04
  dw cTextGroup0A_05
  dw cTextGroup0A_06
  dw cTextGroup0A_07
  dw cTextGroup0A_08
  dw cTextGroup0A_09
  dw cTextGroup0A_0A
  dw cTextGroup0A_0B
  dw cTextGroup0A_0C
  dw cTextGroup0A_0D
  dw cTextGroup0A_0E
  dw cTextGroup0A_0F
  dw cTextGroup0A_10
  dw cTextGroup0A_11

SECTION "Text_0A", ROMX[$405D], BANK[$6A]
  INCBIN cText_0A

SECTION "Text Bank 0B", ROMX[$4039], BANK[$6B]
TextBank0B::
  dw cTextGroup0B_00
  dw cTextGroup0B_01
  dw cTextGroup0B_02
  dw cTextGroup0B_03
  dw cTextGroup0B_04

SECTION "Text_0B", ROMX[$4043], BANK[$6B]
  INCBIN cText_0B

SECTION "Text Bank 0C", ROMX[$4039], BANK[$6C]
TextBank0C::
  dw cTextGroup0C_00
  dw cTextGroup0C_01

SECTION "Text_0C", ROMX[$403D], BANK[$6C]
  INCBIN cText_0C

SECTION "Text Bank 0D", ROMX[$4039], BANK[$6D]
TextBank0D::
  dw cTextGroup0D_00
  dw cTextGroup0D_01
  dw cTextGroup0D_02
  dw cTextGroup0D_03
  dw cTextGroup0D_04
  dw cTextGroup0D_05
  dw cTextGroup0D_06

SECTION "Text_0D", ROMX[$4047], BANK[$6D]
  INCBIN cText_0D

SECTION "Text Bank 0E", ROMX[$4039], BANK[$6E]
TextBank0E::
  dw cTextGroup0E_00
  dw cTextGroup0E_01
  dw cTextGroup0E_02
  dw cTextGroup0E_03
  dw cTextGroup0E_04
  dw cTextGroup0E_05
  dw cTextGroup0E_06
  dw cTextGroup0E_07
  dw cTextGroup0E_08
  dw cTextGroup0E_09
  dw cTextGroup0E_0A
  dw cTextGroup0E_0B
  dw cTextGroup0E_0C
  dw cTextGroup0E_0D
  dw cTextGroup0E_0E
  dw cTextGroup0E_0F
  dw cTextGroup0E_10
  dw cTextGroup0E_11
  dw cTextGroup0E_12
  dw cTextGroup0E_13
  dw cTextGroup0E_14

SECTION "Text_0E", ROMX[$4063], BANK[$6E]
  INCBIN cText_0E

SECTION "Text Bank 0F", ROMX[$4039], BANK[$6F]
TextBank0F::
  dw cTextGroup0F_00
  dw cTextGroup0F_01
  dw cTextGroup0F_02
  dw cTextGroup0F_03
  dw cTextGroup0F_04
  dw cTextGroup0F_05
  dw cTextGroup0F_06
  dw cTextGroup0F_07

SECTION "Text_0F", ROMX[$4049], BANK[$6F]
  INCBIN cText_0F

SECTION "Text Bank 10", ROMX[$4039], BANK[$78]
TextBank10::
  dw cTextGroup10_00
  dw cTextGroup10_01
  dw cTextGroup10_02
  dw cTextGroup10_03
  dw cTextGroup10_04
  dw cTextGroup10_05

SECTION "Text_10", ROMX[$4045], BANK[$78]
  INCBIN cText_10

SECTION "Text Bank 11", ROMX[$4039], BANK[$79]
TextBank11::
  dw cTextGroup11_00
  dw cTextGroup11_01
  dw cTextGroup11_02
  dw cTextGroup11_03
  dw cTextGroup11_04
  dw cTextGroup11_05

SECTION "Text_11", ROMX[$4045], BANK[$79]
  INCBIN cText_11

