; File initially autogenerated by ./scripts/dump_text.py
INCLUDE "./build/dialog/text_constants.asm"

SECTION "Text banks", ROMX[$4083], BANK[$02]
TextBanks::
  db LOW(BANK(TextBank00))
  db LOW(BANK(TextBank01))
  db LOW(BANK(TextBank02))
  db LOW(BANK(TextBank03))
  db LOW(BANK(TextBank04))
  db LOW(BANK(TextBank05))
  db LOW(BANK(TextBank06))
  db LOW(BANK(TextBank07))
  db LOW(BANK(TextBank08))
  db LOW(BANK(TextBank09))
  db LOW(BANK(TextBank0A))
  db LOW(BANK(TextBank0B))
  db LOW(BANK(TextBank0C))
  db LOW(BANK(TextBank0D))
  db LOW(BANK(TextBank0E))
  db LOW(BANK(TextBank0F))
  db LOW(BANK(TextBank10))
  db LOW(BANK(TextBank11))
  db LOW(BANK(TextBank12))
  db LOW(BANK(TextBank13))
  db LOW(BANK(TextBank14))
  db LOW(BANK(TextBank15))
  db LOW(BANK(TextBank16))
  db LOW(BANK(TextBank17))
  db LOW(BANK(TextBank18))

SECTION "Text Bank 00", ROMX[$4039], BANK[$160]
TextBank00::
  dw cTextGroup00_00
  dw cTextGroup00_01
  dw cTextGroup00_02
  dw cTextGroup00_03
  dw cTextGroup00_04
  dw cTextGroup00_05
  dw cTextGroup00_06
  dw cTextGroup00_07
  dw cTextGroup00_08
  dw cTextGroup00_09
  dw cTextGroup00_0A
  dw cTextGroup00_0B
  dw cTextGroup00_0C
  dw cTextGroup00_0D
  dw cTextGroup00_0E
  INCBIN cText_00

SECTION "Text Bank 01", ROMX[$4039], BANK[$161]
TextBank01::
  dw cTextGroup01_00
  dw cTextGroup01_01
  dw cTextGroup01_02
  dw cTextGroup01_03
  dw cTextGroup01_04
  dw cTextGroup01_05
  INCBIN cText_01

SECTION "Text Bank 02", ROMX[$4039], BANK[$162]
TextBank02::
  dw cTextGroup02_00
  dw cTextGroup02_01
  dw cTextGroup02_02
  dw cTextGroup02_03
  dw cTextGroup02_04
  dw cTextGroup02_05
  dw cTextGroup02_06
  dw cTextGroup02_07
  dw cTextGroup02_08
  dw cTextGroup02_09
  dw cTextGroup02_0A
  dw cTextGroup02_0B
  dw cTextGroup02_0C
  dw cTextGroup02_0D
  dw cTextGroup02_0E
  dw cTextGroup02_0F
  dw cTextGroup02_10
  dw cTextGroup02_11
  dw cTextGroup02_12
  dw cTextGroup02_13
  dw cTextGroup02_14
  INCBIN cText_02

SECTION "Text Bank 03", ROMX[$4039], BANK[$163]
TextBank03::
  dw cTextGroup03_00
  dw cTextGroup03_01
  dw cTextGroup03_02
  dw cTextGroup03_03
  dw cTextGroup03_04
  dw cTextGroup03_05
  dw cTextGroup03_06
  dw cTextGroup03_07
  dw cTextGroup03_08
  dw cTextGroup03_09
  dw cTextGroup03_0A
  dw cTextGroup03_0B
  dw cTextGroup03_0C
  dw cTextGroup03_0D
  dw cTextGroup03_0E
  dw cTextGroup03_0F
  dw cTextGroup03_10
  dw cTextGroup03_11
  dw cTextGroup03_12
  dw cTextGroup03_13
  dw cTextGroup03_14
  dw cTextGroup03_15
  dw cTextGroup03_16
  INCBIN cText_03

SECTION "Text Bank 04", ROMX[$4039], BANK[$164]
TextBank04::
  dw cTextGroup04_00
  dw cTextGroup04_01
  dw cTextGroup04_02
  dw cTextGroup04_03
  INCBIN cText_04

SECTION "Text Bank 05", ROMX[$4039], BANK[$165]
TextBank05::
  dw cTextGroup05_00
  dw cTextGroup05_01
  dw cTextGroup05_02
  dw cTextGroup05_03
  dw cTextGroup05_04
  dw cTextGroup05_05
  dw cTextGroup05_06
  dw cTextGroup05_07
  dw cTextGroup05_08
  dw cTextGroup05_09
  INCBIN cText_05

SECTION "Text Bank 06", ROMX[$4039], BANK[$166]
TextBank06::
  dw cTextGroup06_00
  dw cTextGroup06_01
  dw cTextGroup06_02
  dw cTextGroup06_03
  dw cTextGroup06_04
  INCBIN cText_06

SECTION "Text Bank 07", ROMX[$4039], BANK[$167]
TextBank07::
  dw cTextGroup07_00
  dw cTextGroup07_01
  dw cTextGroup07_02
  dw cTextGroup07_03
  dw cTextGroup07_04
  dw cTextGroup07_05
  dw cTextGroup07_06
  dw cTextGroup07_07
  dw cTextGroup07_08
  dw cTextGroup07_09
  dw cTextGroup07_0A
  INCBIN cText_07

SECTION "Text Bank 08", ROMX[$4039], BANK[$168]
TextBank08::
  dw cTextGroup08_00
  dw cTextGroup08_01
  dw cTextGroup08_02
  dw cTextGroup08_03
  dw cTextGroup08_04
  dw cTextGroup08_05
  INCBIN cText_08

SECTION "Text Bank 09", ROMX[$4039], BANK[$169]
TextBank09::
  dw cTextGroup09_00
  dw cTextGroup09_01
  dw cTextGroup09_02
  dw cTextGroup09_03
  dw cTextGroup09_04
  dw cTextGroup09_05
  dw cTextGroup09_06
  dw cTextGroup09_07
  dw cTextGroup09_08
  dw cTextGroup09_09
  dw cTextGroup09_0A
  dw cTextGroup09_0B
  dw cTextGroup09_0C
  INCBIN cText_09

SECTION "Text Bank 0A", ROMX[$4039], BANK[$16A]
TextBank0A::
  dw cTextGroup0A_00
  dw cTextGroup0A_01
  dw cTextGroup0A_02
  dw cTextGroup0A_03
  dw cTextGroup0A_04
  dw cTextGroup0A_05
  dw cTextGroup0A_06
  dw cTextGroup0A_07
  dw cTextGroup0A_08
  dw cTextGroup0A_09
  dw cTextGroup0A_0A
  dw cTextGroup0A_0B
  dw cTextGroup0A_0C
  INCBIN cText_0A

SECTION "Text Bank 0B", ROMX[$4039], BANK[$16B]
TextBank0B::
  dw cTextGroup0B_00
  dw cTextGroup0B_01
  dw cTextGroup0B_02
  dw cTextGroup0B_03
  INCBIN cText_0B

SECTION "Text Bank 0C", ROMX[$4039], BANK[$16C]
TextBank0C::
  dw cTextGroup0C_00
  dw cTextGroup0C_01
  INCBIN cText_0C

SECTION "Text Bank 0D", ROMX[$4039], BANK[$16D]
TextBank0D::
  dw cTextGroup0D_00
  dw cTextGroup0D_01
  dw cTextGroup0D_02
  INCBIN cText_0D

SECTION "Text Bank 0E", ROMX[$4039], BANK[$16E]
TextBank0E::
  dw cTextGroup0E_00
  dw cTextGroup0E_01
  dw cTextGroup0E_02
  dw cTextGroup0E_03
  dw cTextGroup0E_04
  dw cTextGroup0E_05
  dw cTextGroup0E_06
  dw cTextGroup0E_07
  dw cTextGroup0E_08
  dw cTextGroup0E_09
  dw cTextGroup0E_0A
  dw cTextGroup0E_0B
  dw cTextGroup0E_0C
  dw cTextGroup0E_0D
  dw cTextGroup0E_0E
  INCBIN cText_0E

SECTION "Text Bank 0F", ROMX[$4039], BANK[$16F]
TextBank0F::
  dw cTextGroup0F_00
  dw cTextGroup0F_01
  dw cTextGroup0F_02
  dw cTextGroup0F_03
  INCBIN cText_0F

SECTION "Text Bank 10", ROMX[$4039], BANK[$170]
TextBank10::
  dw cTextGroup10_00
  dw cTextGroup10_01
  dw cTextGroup10_02
  INCBIN cText_10

SECTION "Text Bank 11", ROMX[$4039], BANK[$171]
TextBank11::
  dw cTextGroup11_00
  dw cTextGroup11_01
  dw cTextGroup11_02
  dw cTextGroup11_03
  dw cTextGroup11_04
  dw cTextGroup11_05
  dw cTextGroup11_06
  dw cTextGroup11_07
  dw cTextGroup11_08
  dw cTextGroup11_09
  dw cTextGroup11_0A
  dw cTextGroup11_0B
  INCBIN cText_11

SECTION "Text Bank 12", ROMX[$4039], BANK[$172]
TextBank12::
  dw cTextGroup12_00
  dw cTextGroup12_01
  dw cTextGroup12_02
  dw cTextGroup12_03
  INCBIN cText_12

SECTION "Text Bank 13", ROMX[$4039], BANK[$173]
TextBank13::
  dw cTextGroup13_00
  INCBIN cText_13

SECTION "Text Bank 14", ROMX[$4039], BANK[$174]
TextBank14::
  dw cTextGroup14_00
  INCBIN cText_14

SECTION "Text Bank 15", ROMX[$4039], BANK[$175]
TextBank15::
  dw cTextGroup15_00
  dw cTextGroup15_01
  dw cTextGroup15_02
  dw cTextGroup15_03
  INCBIN cText_15

SECTION "Text Bank 16", ROMX[$4039], BANK[$176]
TextBank16::
  dw cTextGroup16_00
  dw cTextGroup16_01
  dw cTextGroup16_02
  dw cTextGroup16_03
  dw cTextGroup16_04
  INCBIN cText_16

SECTION "Text Bank 17", ROMX[$4039], BANK[$177]
TextBank17::
  dw cTextGroup17_00
  dw cTextGroup17_01
  dw cTextGroup17_02
  dw cTextGroup17_03
  INCBIN cText_17

SECTION "Text Bank 18", ROMX[$4039], BANK[$178]
TextBank18::
  dw cTextGroup18_00
  dw cTextGroup18_01
  dw cTextGroup18_02
  dw cTextGroup18_03
  dw cTextGroup18_04
  dw cTextGroup18_05
  dw cTextGroup18_06
  dw cTextGroup18_07
  dw cTextGroup18_08
  INCBIN cText_18